# fly.toml app configuration file generated for elitebackend on 2024-07-17T17:29:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elitebackend'
primary_region = 'scl'
[env]
  PORT = "3000"

[build]

[deploy]
  release_command = "npx sequelize-cli db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
